In [1]:
import sys
sys.path.append(r'C:/Users/vshnu/OneDrive/Desktop/Vishnuperson/RE/aspire_')
from connector import data_fetch_v2

In [2]:
import pandas as pd

In [3]:
transaction_df.dtypes

NameError: name 'transaction_df' is not defined

In [5]:
transaction = f"""
select user_id, created_time
from merchant_payments where status = "success" """
flag,transaction_df, error_msg = data_fetch_v2(transaction, host="13.126.97.63")

                                     user_id        created_time
0       41c99020-32a6-4911-afd3-313f08de9e03 2020-11-14 01:24:00
1       41c99020-32a6-4911-afd3-313f08de9e03 2020-11-14 01:55:31
2       a832e010-c86c-434c-8f3f-9c3d8c843617 2020-11-15 03:21:20
3       1f2b7fe3-77e6-43e3-96aa-7cf85f7f838e 2020-11-15 13:40:12
4       a832e010-c86c-434c-8f3f-9c3d8c843617 2020-11-15 17:03:06
...                                      ...                 ...
373717  7f8fac1d-1e37-4eb3-a4b4-e79e300671db 2025-02-11 12:33:46
373718  e564e863-5d39-4939-9e32-2e0ea89b4fdc 2025-02-11 13:30:49
373719  31dce5e4-3288-4fa1-ad04-407bd17ff3af 2025-02-11 15:16:36
373720  87875520-9894-4a63-92a7-3114ad5ae341 2025-02-11 16:28:27
373721  1f14b406-e883-4df6-af3a-55d14201bc13 2025-02-11 16:28:44

[373722 rows x 2 columns]
                                     user_id        created_time
0       41c99020-32a6-4911-afd3-313f08de9e03 2020-11-14 01:24:00
1       41c99020-32a6-4911-afd3-313f08de9e03 2020-11-14 01:55:31
2       a832e010-c86c-434c-8f3f-9c3d8c843617 2020-11-15 03:21:20
3       1f2b7fe3-77e6-43e3-96aa-7cf85f7f838e 2020-11-15 13:40:12
4       a832e010-c86c-434c-8f3f-9c3d8c843617 2020-11-15 17:03:06
...                                      ...                 ...
373717  7f8fac1d-1e37-4eb3-a4b4-e79e300671db 2025-02-11 12:33:46
373718  e564e863-5d39-4939-9e32-2e0ea89b4fdc 2025-02-11 13:30:49
373719  31dce5e4-3288-4fa1-ad04-407bd17ff3af 2025-02-11 15:16:36
373720  87875520-9894-4a63-92a7-3114ad5ae341 2025-02-11 16:28:27
373721  1f14b406-e883-4df6-af3a-55d14201bc13 2025-02-11 16:28:44

[373722 rows x 2 columns]

In [6]:
transaction_df.dtypes

user_id                 object
created_time    datetime64[ns]
dtype: object

In [8]:
transaction_df.rename(columns={"created_time":"txn_date"})

                                     user_id            txn_date
0       41c99020-32a6-4911-afd3-313f08de9e03 2020-11-14 01:24:00
1       41c99020-32a6-4911-afd3-313f08de9e03 2020-11-14 01:55:31
2       a832e010-c86c-434c-8f3f-9c3d8c843617 2020-11-15 03:21:20
3       1f2b7fe3-77e6-43e3-96aa-7cf85f7f838e 2020-11-15 13:40:12
4       a832e010-c86c-434c-8f3f-9c3d8c843617 2020-11-15 17:03:06
...                                      ...                 ...
373717  7f8fac1d-1e37-4eb3-a4b4-e79e300671db 2025-02-11 12:33:46
373718  e564e863-5d39-4939-9e32-2e0ea89b4fdc 2025-02-11 13:30:49
373719  31dce5e4-3288-4fa1-ad04-407bd17ff3af 2025-02-11 15:16:36
373720  87875520-9894-4a63-92a7-3114ad5ae341 2025-02-11 16:28:27
373721  1f14b406-e883-4df6-af3a-55d14201bc13 2025-02-11 16:28:44

[373722 rows x 2 columns]

In [9]:
transaction_df["txn_date"] = transaction_df["txn_date"].dt.to_timestamp()

KeyError: 'txn_date'

In [ ]:
transaction_df["cohort_month"] = transaction_df.groupby("user_id")["txn_date"].transform("min").dt.to_period("M")

NameError: name 'transaction_df' is not defined

In [ ]:
cohort_data = transaction_df.pivot_table(index="cohort_month", columns="txn_date", values="user_id", aggfunc="nunique")

In [ ]:
cohort_data.to_csv('cohort_data.csv')

In [56]:
transaction_df

,user_id,created_time,txn_date,cohort_month
0,41c99020-32a6-4911-afd3-313f08de9e03,2020-11-14 01:24:00,2020-11-01,2020-11
1,41c99020-32a6-4911-afd3-313f08de9e03,2020-11-14 01:55:31,2020-11-01,2020-11
2,a832e010-c86c-434c-8f3f-9c3d8c843617,2020-11-15 03:21:20,2020-11-01,2020-11
3,1f2b7fe3-77e6-43e3-96aa-7cf85f7f838e,2020-11-15 13:40:12,2020-11-01,2020-11
4,a832e010-c86c-434c-8f3f-9c3d8c843617,2020-11-15 17:03:06,2020-11-01,2020-11
...,...,...,...,...
373682,a613abcd-8ba3-46e8-b6ed-3d1db6a1a8ee,2025-02-06 10:26:19,2025-02-01,2024-10
373683,a613abcd-8ba3-46e8-b6ed-3d1db6a1a8ee,2025-02-06 10:27:38,2025-02-01,2024-10
373684,1a282bc0-9a69-4fc0-96c3-53fbcf2d403a,2025-02-06 10:37:52,2025-02-01,2024-10
373685,c70ce214-2ebc-4e9b-b7ca-33869a4bd525,2025-02-06 11:38:10,2025-02-01,2024-10
373686,1617f997-1362-46de-8c19-5e0dcd853da8,2025-02-06 13:16:15,2025-02-01,2024-10