In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\vshnu\OneDrive\Desktop\Vishnuperson\RE\aspire_\learn\Datacamp\dummy_data_prctaise\data_for_pivot_manipulation.csv")

In [4]:
df

          City  Year  Temperature
0     New York  2020           15
1     New York  2021           14
2     New York  2022           16
3  Los Angeles  2020           25
4  Los Angeles  2021           26
5  Los Angeles  2022           24
6      Chicago  2020           10
7      Chicago  2021           11
8      Chicago  2022            9

In [6]:
pivots = df.pivot_table("Temperature", index="City", columns="Year")
pivots

Year         2020  2021  2022
City
Chicago      10.0  11.0   9.0
Los Angeles  25.0  26.0  24.0
New York     15.0  14.0  16.0

In [12]:
pivots.index

Index(['Chicago', 'Los Angeles', 'New York'], dtype='object', name='City')

In [8]:
#Get the mean temp by year

mean_temp_by_year = pivots.mean()
mean_temp_by_year

Year
2020    16.666667
2021    17.000000
2022    16.333333
dtype: float64

In [14]:
mean_temp_by_year.max()

np.float64(17.0)

In [13]:
# Filter for the year that had the highest mean temp
print(mean_temp_by_year[mean_temp_by_year == mean_temp_by_year.max()])

Year
2021    17.0
dtype: float64

In [15]:
# Get the mean temp by city
mean_by_city = pivots.mean(axis="columns")
mean_by_city

City
Chicago        10.0
Los Angeles    25.0
New York       15.0
dtype: float64

In [16]:
# Filter for the city that had the lowest mean temp

print(mean_by_city[mean_by_city == mean_by_city.min()])

City
Chicago    10.0
dtype: float64