In [1]:
import pandas as pd

# Data upload & sanity check

In [ ]:
bonus_cost = pd.read_excel(r"C:\Users\vshnu\OneDrive\Desktop\Vishnuperson\RE\aspire_\learn\Full_projects\Game_analytics_lognormal\BonusCost_Data.xlsx")
first_bet = pd.read_excel(r"C:\Users\vshnu\OneDrive\Desktop\Vishnuperson\RE\aspire_\learn\Full_projects\Game_analytics_lognormal\First_Bet_Data.xlsx")
first_deposit = pd.read_excel(r"C:\Users\vshnu\OneDrive\Desktop\Vishnuperson\RE\aspire_\learn\Full_projects\Game_analytics_lognormal\First_Deposit_Data.xlsx")
Pl_activity = pd.read_excel(r"C:\Users\vshnu\OneDrive\Desktop\Vishnuperson\RE\aspire_\learn\Full_projects\Game_analytics_lognormal\Player_Activity_Data.xlsx")
pl_details = pd.read_excel(r"C:\Users\vshnu\OneDrive\Desktop\Vishnuperson\RE\aspire_\learn\Full_projects\Game_analytics_lognormal\Player_Details.xlsx")

In [78]:
first_deposit = pd.read_excel(r"C:\Users\vshnu\OneDrive\Desktop\Vishnuperson\RE\aspire_\learn\Full_projects\Game_analytics_lognormal\First_Deposit_Data.xlsx")

In [48]:
bonus_cost.columns = bonus_cost.iloc[0]
bonus_cost = bonus_cost[1:].reset_index(drop=True)

# first_bet.columns = first_bet.iloc[0]
# first_bet = first_bet[1:].reset_index(drop=True)

# first_deposit.columns = first_deposit.iloc[0]
# first_deposit = first_deposit[1:].reset_index(drop=True)

# Pl_activity.columns = Pl_activity.iloc[0]
# Pl_activity = Pl_activity[1:].reset_index(drop=True)

# pl_details.columns = pl_details.iloc[0]
# pl_details = pl_details[1:].reset_index(drop=True)

In [ ]:
bonus_cost = bonus_cost.drop(bonus_cost.columns[0], axis=1)

In [53]:
bonus_cost.describe()

C:\Users\vshnu\AppData\Local\Temp\ipykernel_26512\3204865855.py:1: FutureWarning: The behavior of value_counts with object-dtype is deprecated. In a future version, this will *not* perform dtype inference on the resulting index. To retain the old behavior, use `result.index = result.index.infer_objects()`
  bonus_cost.describe()

0       Src_PLAYER_ID        ActivityMonth  Product  BONUS_COST
count          207070               207070   207070      207070
unique         100749                   30        2        7518
top          12412144  2021-04-30 00:00:00  eGaming          50
freq               36                12895   150191       19114

In [40]:
bonus_cost["Product"].value_counts()

Product
eGaming       150191
SportsBook     56879
Name: count, dtype: int64

In [63]:
first_deposit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 292785 entries, 0 to 292784
Data columns (total 5 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Src_Player_Id          292785 non-null  object
 1   First_Deposit_Date     127261 non-null  object
 2   First_Deposit_Channel  127261 non-null  object
 3   First_Deposit_Method   127261 non-null  object
 4   First_Deposit_Amount   127261 non-null  object
dtypes: object(5)
memory usage: 11.2+ MB

In [81]:
first_deposit = first_deposit.drop(first_deposit.columns[0], axis=1)

In [82]:
first_deposit.head(2)

,Src_Player_Id,First_Deposit_Date,First_Deposit_Channel,First_Deposit_Method,First_Deposit_Amount
0,13472812,NaN,NaN,NaN,NaN
1,13331793,NaN,NaN,NaN,NaN

In [80]:
first_deposit.columns = first_deposit.iloc[0]
first_deposit = first_deposit[1:].reset_index(drop=True)

In [83]:
first_deposit["First_Deposit_Channel"].value_counts()

First_Deposit_Channel
Online    98483
Retail    28778
Name: count, dtype: int64

In [84]:
first_deposit["First_Deposit_Method"].value_counts()

First_Deposit_Method
VISA                 53677
RetailDeposit        28778
MC                   27880
PaysafecardViaSC     13589
MAESTRO               2664
MoneyBookersViaSC      599
NetellerviaSC           71
Correction               3
Name: count, dtype: int64

In [87]:
first_bet.head(2)

,Src_Player_Id,System_First_Bet_Datetime,System_First_BetSlip_Amt,System_First_Bet_Product_Group,System_First_Bet_Product,System_First_Bet_Channel,System_First_Bet_Platform
0,15643431,2020-10-09 03:57:29,2.5,eGaming,Non Table Games,Online,Mobile
1,13593034,2019-09-27 15:03:58.244000,10,Sports,Prematch,Online,Mobile

In [86]:
first_bet = first_bet.drop(first_bet.columns[0], axis=1)

In [88]:
first_bet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 292785 entries, 0 to 292784
Data columns (total 7 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Src_Player_Id                   292785 non-null  object
 1   System_First_Bet_Datetime       159166 non-null  object
 2   System_First_BetSlip_Amt        159166 non-null  object
 3   System_First_Bet_Product_Group  159166 non-null  object
 4   System_First_Bet_Product        159166 non-null  object
 5   System_First_Bet_Channel        159166 non-null  object
 6   System_First_Bet_Platform       159166 non-null  object
dtypes: object(7)
memory usage: 15.6+ MB

In [89]:
first_bet["System_First_Bet_Product_Group"].value_counts()

System_First_Bet_Product_Group
eGaming    94593
Sports     61351
Lotto       1742
Lottery     1113
IVG          367
Name: count, dtype: int64

In [90]:
first_bet["System_First_Bet_Product"].value_counts()

System_First_Bet_Product
Non Table Games    91147
Prematch           44898
Live               16453
Table Games         3446
Lotto               1742
Lucky Six           1017
IVG                  367
LuckyX                72
Next Six              24
Name: count, dtype: int64

In [92]:
first_bet["System_First_Bet_Platform"].value_counts()

System_First_Bet_Platform
Mobile    127948
Web        31218
Name: count, dtype: int64

In [93]:
first_bet["System_First_Bet_Channel"].value_counts()

System_First_Bet_Channel
Online    159166
Name: count, dtype: int64

In [99]:
Pl_activity.head(2)

,src_player_id,ActivityMonth,Product,SubProduct,ActivePlayerDays,Bet_Amount,Win_Amount,Gross_Win,Net_Gross_Win
0,16585649,2020-08-31 00:00:00,SportsBook,Livebook,1,500,0,500,420
1,12845036,2019-05-31 00:00:00,SportsBook,Prematch,28,1229.48,1177.85,41.63,34.9692

In [95]:
Pl_activity.columns = Pl_activity.iloc[0]
Pl_activity = Pl_activity[1:].reset_index(drop=True)

In [98]:
Pl_activity = Pl_activity.drop(Pl_activity.columns[0], axis =1)

In [102]:
pl_details.head(2)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,Src_Player_Id,Signup_Date,acquisition_channel,src_advertiser_id,Gender,Date_Of_Birth,Internal_Player_YN
1,NaN,12584958,2019-02-23 17:24:49,NaN,999999,M,1991-08-05 00:00:00,N

In [106]:
pl_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 292785 entries, 0 to 292784
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Src_Player_Id        292785 non-null  object
 1   Signup_Date          292785 non-null  object
 2   acquisition_channel  201279 non-null  object
 3   src_advertiser_id    290719 non-null  object
 4   Gender               292774 non-null  object
 5   Date_Of_Birth        292785 non-null  object
 6   Internal_Player_YN   292785 non-null  object
dtypes: object(7)
memory usage: 15.6+ MB

In [ ]:
pl_details.columns = pl_details.iloc[0]
pl_details = pl_details[1:].reset_index(drop=True)

In [105]:
pl_details = pl_details.drop(pl_details.columns[0], axis=1)

# Cohort Analysis

In [290]:
print(pl_details.head(2))
print(Pl_activity.head(2))
print(first_bet.head(2))
print(first_deposit.head(2))
print(bonus_cost.head(2))

0 Src_Player_Id          Signup_Date acquisition_channel src_advertiser_id  \
0      12584958  2019-02-23 17:24:49                 NaN            999999
1      12356925  2019-01-07 15:57:11                 NaN            999999

0 Gender        Date_Of_Birth Internal_Player_YN
0     M   1991-08-05 00:00:00                 N
1     M   1993-09-09 00:00:00                 N
0 src_player_id        ActivityMonth     Product SubProduct ActivePlayerDays  \
0      16585649  2020-08-31 00:00:00  SportsBook   Livebook                1
1      12845036  2019-05-31 00:00:00  SportsBook   Prematch               28

0 Bet_Amount Win_Amount Gross_Win Net_Gross_Win
0        500          0       500           420
1    1229.48    1177.85     41.63       34.9692
0 Src_Player_Id   System_First_Bet_Datetime System_First_BetSlip_Amt  \
0      15643431         2020-10-09 03:57:29                      2.5
1      13593034  2019-09-27 15:03:58.244000                       10

0 System_First_Bet_Product_Group System_First_Bet_Product  \
0                        eGaming          Non Table Games
1                         Sports                 Prematch

0 System_First_Bet_Channel System_First_Bet_Platform
0                   Online                    Mobile
1                   Online                    Mobile
0 Src_Player_Id First_Deposit_Date First_Deposit_Channel First_Deposit_Method  \
0      13472812                NaN                   NaN                  NaN
1      13331793                NaN                   NaN                  NaN

0 First_Deposit_Amount
0                  NaN
1                  NaN
0 Src_PLAYER_ID        ActivityMonth  Product BONUS_COST
0      16051927  2020-06-30 00:00:00  eGaming         50
1      19309540  2021-02-28 00:00:00  eGaming         40

In [291]:
# data needed: Src_Player_Id ,Signup_Date, acquisition_channel,
# src_player_id        ActivityMonth     Product Net_Gross_Win  ,
# BONUS_COST, Src_PLAYER_ID  , ActivityMonth

In [292]:
Pl_activity_ca = Pl_activity[["src_player_id", "ActivityMonth","Product","Net_Gross_Win","ActivePlayerDays"]]

In [293]:
bonus_cost.head(1)

0 Src_PLAYER_ID        ActivityMonth  Product BONUS_COST
0      16051927  2020-06-30 00:00:00  eGaming         50

In [294]:
Pl_activity_ca = Pl_activity_ca.merge(bonus_cost, how="left", left_on=["src_player_id", "ActivityMonth"],
                                      right_on=["Src_PLAYER_ID","ActivityMonth"])

In [295]:
Pl_activity_ca.head(2)

,src_player_id,ActivityMonth,Product_x,Net_Gross_Win,ActivePlayerDays,Src_PLAYER_ID,Product_y,BONUS_COST
0,16585649,2020-08-31 00:00:00,SportsBook,420,1,NaN,NaN,NaN
1,12845036,2019-05-31 00:00:00,SportsBook,34.9692,28,NaN,NaN,NaN

In [296]:
Pl_activity_ca = Pl_activity_ca.drop(columns=["Product_y","Src_PLAYER_ID"])

In [297]:
pl_details.head(2)

,Src_Player_Id,Signup_Date,acquisition_channel,src_advertiser_id,Gender,Date_Of_Birth,Internal_Player_YN
0,12584958,2019-02-23 17:24:49,NaN,999999,M,1991-08-05 00:00:00,N
1,12356925,2019-01-07 15:57:11,NaN,999999,M,1993-09-09 00:00:00,N

In [298]:
pl_details_sub = pl_details[["Src_Player_Id","Signup_Date","acquisition_channel"	]]

In [299]:
Pl_activity_ca = Pl_activity_ca.merge(pl_details_sub, how="left", left_on="src_player_id",
                                      right_on="Src_Player_Id")

### final data for cohort analysis

In [300]:
Pl_activity_ca.head(2)

,src_player_id,ActivityMonth,Product_x,Net_Gross_Win,ActivePlayerDays,BONUS_COST,Src_Player_Id,Signup_Date,acquisition_channel
0,16585649,2020-08-31 00:00:00,SportsBook,420,1,NaN,16585649,2020-08-06 12:27:56,PPC
1,12845036,2019-05-31 00:00:00,SportsBook,34.9692,28,NaN,12845036,2019-04-20 22:05:39,PPC

In [301]:
Pl_activity_ca["revenue"] = Pl_activity_ca["Net_Gross_Win"] - Pl_activity_ca["BONUS_COST"]

In [302]:
# get cohort month (y-m format), get activity_month (y-m fomart), get_period (cohort_month-activity month)

In [303]:
Pl_activity_ca.dtypes

0
src_player_id          object
ActivityMonth          object
Product_x              object
Net_Gross_Win          object
ActivePlayerDays       object
BONUS_COST             object
Src_Player_Id          object
Signup_Date            object
acquisition_channel    object
revenue                object
dtype: object

In [304]:
Pl_activity_ca["ActivityMonth"] = pd.to_datetime(Pl_activity_ca["ActivityMonth"])
Pl_activity_ca["Signup_Date"] = pd.to_datetime(Pl_activity_ca["Signup_Date"])

In [305]:
Pl_activity_ca["Cohort_month"] =  Pl_activity_ca["Signup_Date"].dt.strftime("%y-%m")

In [306]:
## fucntion to help us get month, year separatly, which will be used to calculate period

def get_m_y(df,column):
    year = df[column].dt.year
    month = df[column].dt.month
    return year, month

In [307]:
act_year, act_month = get_m_y(Pl_activity_ca,"ActivityMonth")
coh_year, coh_month = get_m_y(Pl_activity_ca,"Signup_Date")

In [308]:
Pl_activity_ca["period"] = (act_year-coh_year)*12 + (act_month-coh_month)

In [309]:
Pl_activity_ca.head(2)

,src_player_id,ActivityMonth,Product_x,Net_Gross_Win,ActivePlayerDays,BONUS_COST,Src_Player_Id,Signup_Date,acquisition_channel,revenue,Cohort_month,period
0,16585649,2020-08-31,SportsBook,420,1,NaN,16585649,2020-08-06 12:27:56,PPC,NaN,20-08,0
1,12845036,2019-05-31,SportsBook,34.9692,28,NaN,12845036,2019-04-20 22:05:39,PPC,NaN,19-04,1

In [310]:
coh_by_month1 = Pl_activity_ca.groupby(["Cohort_month", "period"]).agg(
    user_count=("src_player_id", "count"),
    total_revenue=("revenue", "sum")
).reset_index()

In [311]:
type(coh_by_month1)

pandas.core.frame.DataFrame

In [312]:
coh_by_month1.head(1)

  Cohort_month  period  user_count total_revenue
0        19-01       0        8590 -45174.063188

In [313]:
initial_users = coh_by_month1[coh_by_month1["period"] == 0][["Cohort_month", "user_count"]]

In [314]:
initial_users.head(1)

  Cohort_month  user_count
0        19-01        8590

In [315]:
initial_users = initial_users.rename(columns={"user_count":"initial_users"})

In [316]:
coh_by_month1 = coh_by_month1.merge(initial_users, on="Cohort_month")

In [317]:
coh_by_month1.head(1)

  Cohort_month  period  user_count total_revenue  initial_users
0        19-01       0        8590 -45174.063188           8590

In [318]:
coh_by_month1["percent_users"] = (coh_by_month1["user_count"]/coh_by_month1["initial_users"])*100

In [319]:
cohort_analysis_month = coh_by_month1.pivot(index="Cohort_month",columns="period",values="percent_users")
cohort_analysis_month

period,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
Cohort_month,,,,,,,,,,,,,,,,,,,,,
19-01,100.0,38.032596,18.917346,18.335274,13.364377,11.350407,10.977881,11.722934,10.977881,12.456345,...,10.686845,13.317811,13.422584,12.968568,14.481956,13.853318,14.004657,13.434226,12.025611,9.941793
19-02,100.0,41.541756,27.320821,18.239073,14.132762,12.961330,14.069782,13.062099,14.157954,15.631692,...,14.674392,14.812949,14.485452,16.664567,17.017257,16.966872,16.009573,15.404963,11.663938,NaN
19-03,100.0,49.343186,24.288451,18.007663,14.928845,15.708812,14.942529,16.584565,17.172961,17.638205,...,14.285714,13.423645,15.394089,15.708812,16.119321,14.956212,14.135194,11.152162,NaN,NaN
19-04,100.0,42.457660,19.285808,15.347250,15.189707,15.570435,15.557306,16.922673,17.027701,15.833005,...,13.456741,15.714848,15.583563,15.452278,14.362610,14.152553,11.513719,NaN,NaN,NaN
19-05,100.0,35.175316,17.138850,16.058906,14.151473,16.072931,17.559607,17.531557,15.918654,15.063114,...,14.165498,14.249649,15.217391,14.333801,14.109397,11.093969,NaN,NaN,NaN,NaN
19-06,100.0,33.925585,20.882107,17.892977,17.683946,16.555184,17.224080,16.806020,15.321906,16.116221,...,14.694816,16.074415,14.590301,13.440635,12.959866,NaN,NaN,NaN,NaN,NaN
19-07,100.0,41.322474,23.792903,21.950747,22.183440,21.330231,19.080861,18.576692,17.374443,11.983711,...,18.596083,17.490789,17.141749,14.194299,NaN,NaN,NaN,NaN,NaN,NaN
19-08,100.0,40.753963,26.003142,22.576039,22.518920,19.605883,17.478224,16.421534,10.181351,9.981437,...,15.950307,15.536199,12.323290,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19-09,100.0,46.737305,27.522936,23.543093,21.062153,18.736271,17.728389,10.608606,10.363096,13.063703,...,15.273291,13.748546,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19-10,100.0,49.229111,28.743935,23.083558,20.377358,19.083558,12.150943,10.803235,13.035040,13.423181,...,13.035040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19-11,100.0,49.283719,23.858005,20.037841,18.343995,10.316245,9.775655,12.523651,12.046130,12.325435,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19-12,100.0,39.943420,20.186165,18.333638,11.005658,9.180507,10.905275,10.759263,11.087790,10.960029,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-01,100.0,38.591881,22.616890,13.084451,10.846321,12.903226,12.404857,12.277999,12.314244,14.316781,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-02,100.0,40.196635,13.083759,10.531291,12.166761,11.353753,10.748724,10.635281,13.565891,13.064852,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-03,100.0,22.702642,12.124633,11.379544,9.686159,9.528110,8.986227,12.203658,12.700384,12.858433,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-04,100.0,20.613713,12.098077,8.500954,7.884305,7.091470,9.807664,10.306857,9.954485,8.691822,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-05,100.0,28.342320,13.313978,10.839209,10.189410,12.401493,13.742569,13.576663,14.475321,12.885386,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-06,100.0,40.212633,20.888055,18.907651,21.325829,21.284136,19.512195,22.117990,21.888680,22.409839,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-07,100.0,40.763922,22.773231,23.126304,22.869523,19.836302,22.564596,22.115230,22.372011,22.067084,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-08,100.0,45.147059,30.349265,24.595588,21.599265,22.040441,23.161765,23.272059,22.205882,20.625000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-09,100.0,68.482357,32.905104,28.143200,28.485783,27.509421,26.841384,25.933539,24.134978,22.028092,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-10,100.0,59.938352,33.560620,32.523818,31.150757,31.094713,29.618905,25.481039,22.903045,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-11,100.0,60.022000,36.285063,30.643514,29.881355,27.461303,25.159111,22.574055,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-12,100.0,52.891089,29.069307,26.108911,24.089109,20.920792,18.871287,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21-01,100.0,54.635427,32.781256,25.610988,22.571198,19.208241,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21-02,100.0,57.085744,30.184114,25.376118,20.915308,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21-03,100.0,56.253057,29.610305,23.112669,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21-04,100.0,51.277596,24.856909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21-05,100.0,45.956552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21-06,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [320]:
cohort_analysis_month.to_csv("cohort_analysis_month.csv")

In [321]:
cohort_analysis_revenue = coh_by_month1.pivot(index="Cohort_month",columns="period",values="total_revenue")
cohort_analysis_revenue

period,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
Cohort_month,,,,,,,,,,,,,,,,,,,,,
19-01,-45174.063188,319274.162417,75349.122708,119558.254065,56015.565683,84405.387647,72409.410434,19846.795612,23015.656221,49134.570832,...,39563.272594,84057.673932,28228.116807,143769.258203,99635.578,36569.22,83819.466,95258.4988,-4141.8044,163855.5296
19-02,64286.949315,-5306.744667,84376.763159,54022.84931,16479.558629,50382.655505,63035.554234,45521.172058,49638.41228,32943.76233,...,42483.558291,89739.395939,149855.238368,24203.0804,25428.2124,35665.2328,-344011.3936,41121.8584,-216.2676,NaN
19-03,9621.029342,9057.641975,78400.701251,43047.335526,97633.763929,64416.798605,66296.932012,107678.781635,172955.031999,75859.667845,...,39841.837826,38450.878117,42242.1424,51091.618,45101.5908,58429.7332,41620.3904,-425264.218,NaN,NaN
19-04,149187.099646,99655.854713,39147.401232,51926.333127,36117.208839,17302.982504,7860.449068,-23742.938006,43647.126352,-4972.685676,...,71019.40218,36238.1144,32316.828,22566.234,26574.9244,55578.5256,48661.3912,NaN,NaN,NaN
19-05,134330.586614,130430.92676,127224.731129,8800.172819,121979.054238,108884.663962,93972.530402,-226749.258718,95295.641206,60157.946275,...,53780.8056,107765.1184,25632.4652,-138827.8916,189129.8448,81344.6016,NaN,NaN,NaN,NaN
19-06,-10144.055342,16277.876017,81366.977405,21887.061986,40620.097943,12569.396223,40792.486991,-1768.136915,35896.374591,84276.148868,...,50518.3612,23004.252,34020.854,32911.4112,-1332.1232,NaN,NaN,NaN,NaN,NaN
19-07,6797.60671,75044.314343,76057.83552,22822.725933,100328.943689,35918.625504,97114.65695,68098.045233,21375.351953,9301.129785,...,16010.8036,21564.4736,6948.4152,40287.5828,NaN,NaN,NaN,NaN,NaN,NaN
19-08,-66259.07897,185356.053831,194636.29898,298220.714421,143945.309889,87928.87276,88.994308,64900.784723,8729.827445,20192.429143,...,60089.1072,29573.2376,97181.8168,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19-09,-69310.146807,108698.369866,241961.870366,439033.101039,55703.636009,39578.405867,56675.520795,-24622.465497,59651.491924,36485.316078,...,78196.3508,118472.7852,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19-10,-37435.413474,162395.623507,-152414.939108,18832.104788,104407.737499,79813.156992,20961.802936,51645.375439,46993.78586,13851.988978,...,-42369.9784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19-11,-190301.503408,81797.026803,89853.598465,170588.772785,-20975.952268,42850.934218,64451.970766,33453.552205,85624.202523,47906.763446,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19-12,-58539.741004,127938.315605,95704.819224,38212.586527,-95553.207551,46196.263975,90119.816428,39897.898805,62788.897016,104086.826385,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-01,-123283.766485,194112.174221,70025.943425,53373.682045,90940.904876,114514.470797,277030.12728,176122.389973,157353.077949,164823.817639,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-02,-307058.098921,53280.709355,-65361.840726,42812.06085,43057.788515,67770.605289,57793.88334,10776.576249,78680.470513,57754.826059,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-03,-90449.580575,228622.341299,115361.250237,64577.998732,86873.401959,49747.201663,56788.311779,45521.932401,124576.541012,96476.565893,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-04,-69599.036003,91079.91229,59985.589053,103056.577022,44235.747345,21563.306709,22720.532325,84865.577063,10812.239463,50290.1928,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-05,-102316.002389,-67001.95764,79539.081797,85815.302169,81939.896605,98566.661761,70942.683337,-74749.785654,14989.6852,45212.9892,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-06,-56350.972818,-192257.218289,72044.171437,-30641.434958,155094.511728,16187.033913,60968.769608,54072.6608,51585.5772,51676.5504,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-07,-154547.577085,56453.549105,94785.075596,114015.967706,51392.080808,64143.030637,49841.3236,66497.1212,63809.0144,63322.216,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-08,-143985.192577,43507.325722,51545.742461,98411.296671,71494.372345,41298.3124,139453.15,63215.3464,-19304.824,55770.4036,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-09,-90573.110087,409054.28667,9711.36828,249368.249967,52004.638,32454.9204,32459.6688,84313.2288,88717.1896,167690.162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-10,238545.467201,17049.023707,234179.647285,186404.2748,225521.0096,121104.338,335290.5076,159540.9132,237690.4672,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-11,-190779.232616,450752.364004,356485.4328,171530.7856,75882.5052,329245.46468,221801.3608,154706.71844,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-12,202766.508866,141286.91,90482.1512,14577.72,85279.3568,184529.842,136267.1016,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21-01,-102294.2,130631.8748,186164.4288,196479.954,186884.3924,61119.5796,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21-02,-257257.2836,126609.0208,162510.08496,118991.7692,76509.0408,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21-03,-509316.6384,425670.9432,228390.3096,-57344.1276,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21-04,-259281.89388,379906.9888,200736.9044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21-05,-93571.044,269197.0176,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21-06,-263475.6764,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [322]:
cohort_analysis_revenue.to_csv("cohort_analysis_revenue.csv")

# Cohort Analysis (DC)

In [352]:
online = pd.read_csv(r"C:\Users\vshnu\OneDrive\Desktop\Vishnuperson\RE\aspire_\learn\Full_projects\Game_analytics_lognormal\online.csv")

In [369]:
online.head(2)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,invoice_month
0,572558,22745,POPPY'S PLAYHOUSE BEDROOM,6,2011-10-25 08:26:00,2.10,14286,United Kingdom,2011-10-01
1,577485,23196,VINTAGE LEAF MAGNETIC NOTEPAD,1,2011-11-20 11:56:00,1.45,16360,United Kingdom,2011-11-01

In [ ]:
#droppning a first colmn which was redundant, usinf frop method on df. , axis=1 is mus, because we want to drop column, column is dentod by axis=1
# default is axis=0, which is denoted by row. so it is important to provide axis=1.
online = online.drop(online.columns[0], axis = 1)

# ?Pl_activity = Pl_activity.drop(Pl_activity.columns[0], axis =1)

In [362]:
import datetime as dt

In [356]:
type(online["InvoiceDate"])

pandas.core.series.Series

In [ ]:
# we use pandas to convert str to datetime
online["InvoiceDate"] = pd.to_datetime(online["InvoiceDate"])

In [367]:
# x is the column (or series) that will be provided, it will return, year, month and day as default 1

def get_month(x):
    return dt.datetime(x.year, x.month, 1)

In [368]:
online["invoice_month"] = online["InvoiceDate"].apply(get_month)

In [ ]:
# get the cohorth month for each sutome rpopluated. for this we use group by (so we group by custoemr id and get invoice monht)
# but use transform method to get only min (given "min" in quotes)
online["Cohort_month"] = online.groupby("CustomerID")["invoice_month"].transform("min")

In [382]:
online.head(1)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,invoice_month,Cohort_month,period
0,572558,22745,POPPY'S PLAYHOUSE BEDROOM,6,2011-10-25 08:26:00,2.1,14286,United Kingdom,2011-10-01,2011-04-01,6

In [378]:
# next we need to get index number. this is on the column
# is num of month bw cohort month and invoice month, if croses a year, it need to be multiplied by 12. 

def m_y(dataf, column):
    year = column.dt.year 
    month = column.dt.month
    return year, month

In [380]:
invoice_yr, invoice_mt = m_y(online, online["InvoiceDate"])
cohort_yr, cohort_mt = m_y(online, online["Cohort_month"])

In [381]:
online["period"] = (invoice_yr-cohort_yr)*12 + (invoice_mt-cohort_mt)

In [385]:
# ch_data = online.groupby(["Cohort_month","period"])["CustomerID"].nunique()
ch_data = online.groupby(["Cohort_month","period"])["CustomerID"].apply(pd.Series.nunique)

In [386]:
ch_data

Cohort_month  period
2010-12-01    0         716
              1         246
              2         221
              3         251
              4         245
                       ...
2011-10-01    1          67
              2          30
2011-11-01    0         291
              1          32
2011-12-01    0          38
Name: CustomerID, Length: 91, dtype: int64

# RFM Analysis

In [323]:
Pl_activity_ca.head(2)

,src_player_id,ActivityMonth,Product_x,Net_Gross_Win,ActivePlayerDays,BONUS_COST,Src_Player_Id,Signup_Date,acquisition_channel,revenue,Cohort_month,period
0,16585649,2020-08-31,SportsBook,420,1,NaN,16585649,2020-08-06 12:27:56,PPC,NaN,20-08,0
1,12845036,2019-05-31,SportsBook,34.9692,28,NaN,12845036,2019-04-20 22:05:39,PPC,NaN,19-04,1

In [325]:
revenue_quartiles = pd.qcut(Pl_activity_ca["revenue"], q=4, labels=range(1,5))

In [ ]:
Pl_activity_ca["revenue_quartiles"] = revenue_quartiles

In [329]:
print(Pl_activity_ca["ActivityMonth"].max())

2021-06-30 00:00:00

In [333]:
last_activity_freq = Pl_activity_ca.groupby("src_player_id")["ActivityMonth"].max().reset_index()
last_activity_freq.rename(columns={"ActivityMonth": "LastActivityDate"}, inplace=True)

In [334]:
last_activity_freq

        src_player_id LastActivityDate
0            12329393       2019-01-31
1            12329407       2019-01-31
2            12329630       2019-01-31
3            12329932       2019-01-31
4            12329942       2019-01-31
...               ...              ...
167322       20701685       2021-06-30
167323       20702081       2021-06-30
167324       20702367       2021-06-30
167325       20703294       2021-06-30
167326       20703585       2021-06-30

[167327 rows x 2 columns]

In [336]:
last_activity_freq["last_date"] = pd.to_datetime("2021-06-30")

In [337]:
# frequency

last_activity_freq["MonthsSinceLastActivity"] = ((last_activity_freq["last_date"].dt.year - last_activity_freq["LastActivityDate"].dt.year) * 12 +
                                            (last_activity_freq["last_date"].dt.month - last_activity_freq["LastActivityDate"].dt.month))

In [347]:
r_labels = list(range(4,0,-1))

In [349]:
last_activity_freq["recency_quartiles"] = recency_quartiles

In [348]:

recency_quartiles = pd.qcut(last_activity_freq["MonthsSinceLastActivity"], q=4, labels=r_labels)

In [350]:
last_activity_freq.head(2)

,src_player_id,LastActivityDate,last_date,MonthsSinceLastActivity,recency_quartiles
0,12329393,2019-01-31,2021-06-30,29,1
1,12329407,2019-01-31,2021-06-30,29,1