In [1]:
import sqlalchemy
import pandas as pd 
import json

In [2]:
cred = { 'user': 'vishnupriya', 'password': 'yFl#Cy3qzWW7f#OrxW4IB!P'}

def data_fetch_v2(query,*, 
                  cred=cred, db='aspiredb', 
                  host="13.235.168.161", **kwargs):
    """
    Fetches data for the given query from the database.

    Args:
        query (str):
        cred (dict): {"user" : "<user name>", "password" : "<password>"}
        db (str): 
        host (str):
        kwargs : 

    Returns:
        success_flag (bool):
        output (pd.DataFrame): 
        error_msg (str):
    """
    success_flag = False
    output = pd.DataFrame()
    error_msg = ""
    db_url = rf"mysql+pymysql://{cred['user']}:{cred['password']}@{host}/{db}"
    engine = sqlalchemy.create_engine(db_url)
    output = pd.read_sql(query, engine, **kwargs)
    print(output)
    success_flag = True

    try:
        db_url = rf"mysql+pymysql://{cred['user']}:{cred['password']}@{host}/{db}"
        engine = sqlalchemy.create_engine(db_url)
        output = pd.read_sql(query, engine, **kwargs)
        print(output)
        success_flag = True
    except Exception as e:
        success_flag = False
        error_msg = f"error in data_fetch, {type(e)._name_}: {str(e)}"
    finally:
        return success_flag, output, error_msg

In [3]:
users = f"""
    select user_id from user_registeration_coupon_code_details where coupon_code in
    ('ESSMART','roinet','gramophone','yodacart','buyume')
"""
f1, b2b_users,error_reason = data_fetch_v2(users,host = "13.126.97.63")

                                  user_id
0    e3023c13-bc6b-4b7b-b08d-ad535ca8ba85
1    8fb0c9e6-a40c-445a-8468-81527f10ff2a
2    f70eb9aa-d40e-4e57-8611-ed9605b5b6de
3    0356a1a9-53a9-4de8-8f5d-839a55566dbf
4    7e0fe297-528b-44fa-93b7-e4048893ae85
..                                    ...
413  a1934adb-c592-4ba0-9596-652606b36a40
414  4ef4a3cb-814c-4e67-8236-a2c5316e6996
415  a7fc7ee1-8cf1-43f0-b111-715dc6843656
416  40240356-db23-40e9-81f4-773b883b1701
417  8195f288-2565-419f-ac5f-f1b4c6819d45

[418 rows x 1 columns]
                                  user_id
0    e3023c13-bc6b-4b7b-b08d-ad535ca8ba85
1    8fb0c9e6-a40c-445a-8468-81527f10ff2a
2    f70eb9aa-d40e-4e57-8611-ed9605b5b6de
3    0356a1a9-53a9-4de8-8f5d-839a55566dbf
4    7e0fe297-528b-44fa-93b7-e4048893ae85
..                                    ...
413  a1934adb-c592-4ba0-9596-652606b36a40
414  4ef4a3cb-814c-4e67-8236-a2c5316e6996
415  a7fc7ee1-8cf1-43f0-b111-715dc6843656
416  40240356-db23-40e9-81f4-773b883b1701
417  8195f288-2565-419f-ac5f-f1b4c6819d45

[418 rows x 1 columns]

In [4]:
reject = f"""
    select user_id, json_extract(output_json, '$.rejection_reason') as reject_js
      from de_looger where purpose = 'bureaucheck'
      and json_extract(output_json, '$.decision.approved') = 0 and user_id in {tuple(b2b_users["user_id"])}
"""
f1, reject_json, error_reason = data_fetch_v2(reject,host = "13.126.97.63")

                                 user_id  \
0   206cf27c-aaf4-4a37-a7d1-c9f30106850c
1   3244d992-8691-4fb1-88a8-2a2d9fced9f5
2   7447d9a7-075a-40de-9448-4dc1b13f1aa2
3   354094cf-6f75-4de5-b975-fd9cb73a15c6
4   8eb8d3e8-49f3-4a72-864c-5599cb291654
5   156dd3dc-7d7b-4fa0-9b5c-fbf2ad40d1af
6   0a7bf86f-826e-477b-9c25-44a48408dc08
7   4a6f1224-1272-4748-a365-624d9552b568
8   1cfe555c-cf70-435b-aa7d-dda2a7e63b56
9   9806f9f4-394e-471e-8192-940420e0659e
10  3359b002-ecc7-4c9c-ac62-08cc7c50e0f0
11  87074e2a-7fd9-468a-9eb0-6f58ff449bf4
12  1008d218-54f4-4064-a5dd-98e4e6d24ad8
13  81a7c91f-c0d0-46bd-8572-923e71a09c7a
14  789b738b-3f99-47dc-92f5-486d4fae1d38
15  0eaf3f4f-7e4c-476b-9dc3-9a497a58ae13
16  3a835e8f-0ee5-48a8-8506-00a7cf08d930
17  50d36f2e-08e9-45e4-aa2c-235059d40de7
18  70d32d0d-ce31-40b2-b974-724f502146d8
19  e25df091-4299-45f5-8d99-54de4ff3b337
20  c1c48e87-1f6b-479e-a5a3-81afc1d56e7e
21  f86aadf6-520b-4e03-99eb-fea2979a12e5
22  a7daceeb-1bdd-4c0c-82f4-b492df6bc50a
23  cdbcec43-369d-47b0-8f62-5acaa015a19d
24  ee7a6923-bc92-42c3-9a1b-08752acd60a0
25  dbb43dfd-2a56-4ab0-a7b3-fd5b3c920345

                                            reject_js
0   [{"code": 1145, "message": "user_and_lead_phon...
1   [{"code": 1000, "message": "0 < age < 20 or ag...
2   [{"code": 1000, "message": "0 < age < 20 or ag...
3   [{"code": 1141, "message": "approved_lead_does...
4   [{"code": 1141, "message": "approved_lead_does...
5   [{"code": 1141, "message": "approved_lead_does...
6   [{"code": 1141, "message": "approved_lead_does...
7   [{"code": 1141, "message": "approved_lead_does...
8   [{"code": 1141, "message": "approved_lead_does...
9   [{"code": 1000, "message": "0 < age < 20 or ag...
10  [{"code": 1145, "message": "user_and_lead_phon...
11  [{"code": 1145, "message": "user_and_lead_phon...
12  [{"code": 1145, "message": "user_and_lead_phon...
13  [{"code": 1145, "message": "user_and_lead_phon...
14  [{"code": 1145, "message": "user_and_lead_phon...
15  [{"code": 1145, "message": "user_and_lead_phon...
16  [{"code": 1145, "message": "user_and_lead_phon...
17  [{"code": 1000, "message": "0 < age < 20 or ag...
18  [{"code": 1145, "message": "user_and_lead_phon...
19  [{"code": 1145, "message": "user_and_lead_phon...
20  [{"code": 1000, "message": "0 < age < 20 or ag...
21  [{"code": 1141, "message": "approved_lead_does...
22  [{"code": 1141, "message": "approved_lead_does...
23  [{"code": 1141, "message": "approved_lead_does...
24  [{"code": 1145, "message": "user_and_lead_phon...
25  [{"code": 1000, "message": "0 < age < 20 or ag...
                                 user_id  \
0   206cf27c-aaf4-4a37-a7d1-c9f30106850c
1   3244d992-8691-4fb1-88a8-2a2d9fced9f5
2   7447d9a7-075a-40de-9448-4dc1b13f1aa2
3   354094cf-6f75-4de5-b975-fd9cb73a15c6
4   8eb8d3e8-49f3-4a72-864c-5599cb291654
5   156dd3dc-7d7b-4fa0-9b5c-fbf2ad40d1af
6   0a7bf86f-826e-477b-9c25-44a48408dc08
7   4a6f1224-1272-4748-a365-624d9552b568
8   1cfe555c-cf70-435b-aa7d-dda2a7e63b56
9   9806f9f4-394e-471e-8192-940420e0659e
10  3359b002-ecc7-4c9c-ac62-08cc7c50e0f0
11  87074e2a-7fd9-468a-9eb0-6f58ff449bf4
12  1008d218-54f4-4064-a5dd-98e4e6d24ad8
13  81a7c91f-c0d0-46bd-8572-923e71a09c7a
14  789b738b-3f99-47dc-92f5-486d4fae1d38
15  0eaf3f4f-7e4c-476b-9dc3-9a497a58ae13
16  3a835e8f-0ee5-48a8-8506-00a7cf08d930
17  50d36f2e-08e9-45e4-aa2c-235059d40de7
18  70d32d0d-ce31-40b2-b974-724f502146d8
19  e25df091-4299-45f5-8d99-54de4ff3b337
20  c1c48e87-1f6b-479e-a5a3-81afc1d56e7e
21  f86aadf6-520b-4e03-99eb-fea2979a12e5
22  a7daceeb-1bdd-4c0c-82f4-b492df6bc50a
23  cdbcec43-369d-47b0-8f62-5acaa015a19d
24  ee7a6923-bc92-42c3-9a1b-08752acd60a0
25  dbb43dfd-2a56-4ab0-a7b3-fd5b3c920345

                                            reject_js
0   [{"code": 1145, "message": "user_and_lead_phon...
1   [{"code": 1000, "message": "0 < age < 20 or ag...
2   [{"code": 1000, "message": "0 < age < 20 or ag...
3   [{"code": 1141, "message": "approved_lead_does...
4   [{"code": 1141, "message": "approved_lead_does...
5   [{"code": 1141, "message": "approved_lead_does...
6   [{"code": 1141, "message": "approved_lead_does...
7   [{"code": 1141, "message": "approved_lead_does...
8   [{"code": 1141, "message": "approved_lead_does...
9   [{"code": 1000, "message": "0 < age < 20 or ag...
10  [{"code": 1145, "message": "user_and_lead_phon...
11  [{"code": 1145, "message": "user_and_lead_phon...
12  [{"code": 1145, "message": "user_and_lead_phon...
13  [{"code": 1145, "message": "user_and_lead_phon...
14  [{"code": 1145, "message": "user_and_lead_phon...
15  [{"code": 1145, "message": "user_and_lead_phon...
16  [{"code": 1145, "message": "user_and_lead_phon...
17  [{"code": 1000, "message": "0 < age < 20 or ag...
18  [{"code": 1145, "message": "user_and_lead_phon...
19  [{"code": 1145, "message": "user_and_lead_phon...
20  [{"code": 1000, "message": "0 < age < 20 or ag...
21  [{"code": 1141, "message": "approved_lead_does...
22  [{"code": 1141, "message": "approved_lead_does...
23  [{"code": 1141, "message": "approved_lead_does...
24  [{"code": 1145, "message": "user_and_lead_phon...
25  [{"code": 1000, "message": "0 < age < 20 or ag...

In [5]:
reject_json

,user_id,reject_js
0,206cf27c-aaf4-4a37-a7d1-c9f30106850c,"[{""code"": 1145, ""message"": ""user_and_lead_phon..."
1,3244d992-8691-4fb1-88a8-2a2d9fced9f5,"[{""code"": 1000, ""message"": ""0 < age < 20 or ag..."
2,7447d9a7-075a-40de-9448-4dc1b13f1aa2,"[{""code"": 1000, ""message"": ""0 < age < 20 or ag..."
3,354094cf-6f75-4de5-b975-fd9cb73a15c6,"[{""code"": 1141, ""message"": ""approved_lead_does..."
4,8eb8d3e8-49f3-4a72-864c-5599cb291654,"[{""code"": 1141, ""message"": ""approved_lead_does..."
5,156dd3dc-7d7b-4fa0-9b5c-fbf2ad40d1af,"[{""code"": 1141, ""message"": ""approved_lead_does..."
6,0a7bf86f-826e-477b-9c25-44a48408dc08,"[{""code"": 1141, ""message"": ""approved_lead_does..."
7,4a6f1224-1272-4748-a365-624d9552b568,"[{""code"": 1141, ""message"": ""approved_lead_does..."
8,1cfe555c-cf70-435b-aa7d-dda2a7e63b56,"[{""code"": 1141, ""message"": ""approved_lead_does..."
9,9806f9f4-394e-471e-8192-940420e0659e,"[{""code"": 1000, ""message"": ""0 < age < 20 or ag..."
10,3359b002-ecc7-4c9c-ac62-08cc7c50e0f0,"[{""code"": 1145, ""message"": ""user_and_lead_phon..."
11,87074e2a-7fd9-468a-9eb0-6f58ff449bf4,"[{""code"": 1145, ""message"": ""user_and_lead_phon..."
12,1008d218-54f4-4064-a5dd-98e4e6d24ad8,"[{""code"": 1145, ""message"": ""user_and_lead_phon..."
13,81a7c91f-c0d0-46bd-8572-923e71a09c7a,"[{""code"": 1145, ""message"": ""user_and_lead_phon..."
14,789b738b-3f99-47dc-92f5-486d4fae1d38,"[{""code"": 1145, ""message"": ""user_and_lead_phon..."
15,0eaf3f4f-7e4c-476b-9dc3-9a497a58ae13,"[{""code"": 1145, ""message"": ""user_and_lead_phon..."
16,3a835e8f-0ee5-48a8-8506-00a7cf08d930,"[{""code"": 1145, ""message"": ""user_and_lead_phon..."
17,50d36f2e-08e9-45e4-aa2c-235059d40de7,"[{""code"": 1000, ""message"": ""0 < age < 20 or ag..."
18,70d32d0d-ce31-40b2-b974-724f502146d8,"[{""code"": 1145, ""message"": ""user_and_lead_phon..."
19,e25df091-4299-45f5-8d99-54de4ff3b337,"[{""code"": 1145, ""message"": ""user_and_lead_phon..."
20,c1c48e87-1f6b-479e-a5a3-81afc1d56e7e,"[{""code"": 1000, ""message"": ""0 < age < 20 or ag..."
21,f86aadf6-520b-4e03-99eb-fea2979a12e5,"[{""code"": 1141, ""message"": ""approved_lead_does..."
22,a7daceeb-1bdd-4c0c-82f4-b492df6bc50a,"[{""code"": 1141, ""message"": ""approved_lead_does..."
23,cdbcec43-369d-47b0-8f62-5acaa015a19d,"[{""code"": 1141, ""message"": ""approved_lead_does..."
24,ee7a6923-bc92-42c3-9a1b-08752acd60a0,"[{""code"": 1145, ""message"": ""user_and_lead_phon..."
25,dbb43dfd-2a56-4ab0-a7b3-fd5b3c920345,"[{""code"": 1000, ""message"": ""0 < age < 20 or ag..."

In [11]:
type(reject_json)

pandas.core.frame.DataFrame

In [6]:
reject_json

,user_id,reject_js
0,206cf27c-aaf4-4a37-a7d1-c9f30106850c,"[{""code"": 1145, ""message"": ""user_and_lead_phon..."
1,3244d992-8691-4fb1-88a8-2a2d9fced9f5,"[{""code"": 1000, ""message"": ""0 < age < 20 or ag..."
2,7447d9a7-075a-40de-9448-4dc1b13f1aa2,"[{""code"": 1000, ""message"": ""0 < age < 20 or ag..."
3,354094cf-6f75-4de5-b975-fd9cb73a15c6,"[{""code"": 1141, ""message"": ""approved_lead_does..."
4,8eb8d3e8-49f3-4a72-864c-5599cb291654,"[{""code"": 1141, ""message"": ""approved_lead_does..."
5,156dd3dc-7d7b-4fa0-9b5c-fbf2ad40d1af,"[{""code"": 1141, ""message"": ""approved_lead_does..."
6,0a7bf86f-826e-477b-9c25-44a48408dc08,"[{""code"": 1141, ""message"": ""approved_lead_does..."
7,4a6f1224-1272-4748-a365-624d9552b568,"[{""code"": 1141, ""message"": ""approved_lead_does..."
8,1cfe555c-cf70-435b-aa7d-dda2a7e63b56,"[{""code"": 1141, ""message"": ""approved_lead_does..."
9,9806f9f4-394e-471e-8192-940420e0659e,"[{""code"": 1000, ""message"": ""0 < age < 20 or ag..."
10,3359b002-ecc7-4c9c-ac62-08cc7c50e0f0,"[{""code"": 1145, ""message"": ""user_and_lead_phon..."
11,87074e2a-7fd9-468a-9eb0-6f58ff449bf4,"[{""code"": 1145, ""message"": ""user_and_lead_phon..."
12,1008d218-54f4-4064-a5dd-98e4e6d24ad8,"[{""code"": 1145, ""message"": ""user_and_lead_phon..."
13,81a7c91f-c0d0-46bd-8572-923e71a09c7a,"[{""code"": 1145, ""message"": ""user_and_lead_phon..."
14,789b738b-3f99-47dc-92f5-486d4fae1d38,"[{""code"": 1145, ""message"": ""user_and_lead_phon..."
15,0eaf3f4f-7e4c-476b-9dc3-9a497a58ae13,"[{""code"": 1145, ""message"": ""user_and_lead_phon..."
16,3a835e8f-0ee5-48a8-8506-00a7cf08d930,"[{""code"": 1145, ""message"": ""user_and_lead_phon..."
17,50d36f2e-08e9-45e4-aa2c-235059d40de7,"[{""code"": 1000, ""message"": ""0 < age < 20 or ag..."
18,70d32d0d-ce31-40b2-b974-724f502146d8,"[{""code"": 1145, ""message"": ""user_and_lead_phon..."
19,e25df091-4299-45f5-8d99-54de4ff3b337,"[{""code"": 1145, ""message"": ""user_and_lead_phon..."
20,c1c48e87-1f6b-479e-a5a3-81afc1d56e7e,"[{""code"": 1000, ""message"": ""0 < age < 20 or ag..."
21,f86aadf6-520b-4e03-99eb-fea2979a12e5,"[{""code"": 1141, ""message"": ""approved_lead_does..."
22,a7daceeb-1bdd-4c0c-82f4-b492df6bc50a,"[{""code"": 1141, ""message"": ""approved_lead_does..."
23,cdbcec43-369d-47b0-8f62-5acaa015a19d,"[{""code"": 1141, ""message"": ""approved_lead_does..."
24,ee7a6923-bc92-42c3-9a1b-08752acd60a0,"[{""code"": 1145, ""message"": ""user_and_lead_phon..."
25,dbb43dfd-2a56-4ab0-a7b3-fd5b3c920345,"[{""code"": 1000, ""message"": ""0 < age < 20 or ag..."

In [7]:
#convert to dict
reject_dict = reject_json.to_dict(orient='records')

In [12]:
type(reject_dict)

list

In [15]:
reject_dict

[{'user_id': '206cf27c-aaf4-4a37-a7d1-c9f30106850c',
  'reject_js': '[{"code": 1145, "message": "user_and_lead_phone_mismatch"}]'},
 {'user_id': 'e25df091-4299-45f5-8d99-54de4ff3b337',
  'reject_js': '[{"code": 1145, "message": "user_and_lead_phone_mismatch"}]'},
 {'user_id': '3244d992-8691-4fb1-88a8-2a2d9fced9f5',
  'reject_js': '[{"code": 1000, "message": "0 < age < 20 or age > 55"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]'},
 {'user_id': '7447d9a7-075a-40de-9448-4dc1b13f1aa2',
  'reject_js': '[{"code": 1000, "message": "0 < age < 20 or age > 55"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]'},
 {'user_id': 'c1c48e87-1f6b-479e-a5a3-81afc1d56e7e',
  'reject_js': '[{"code": 1000, "message": "0 < age < 20 or age > 55"}]'},
 {'user_id': '354094cf-6f75-4de5-b975-fd9cb73a15c6',
  'reject_js': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]'},
 {'user_id': '8eb8d3e8-49f3-4a72-864c-5599cb291654',
  'reject_js': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]'},
 {'user_id': '156dd3dc-7d7b-4fa0-9b5c-fbf2ad40d1af',
  'reject_js': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]'},
 {'user_id': 'f86aadf6-520b-4e03-99eb-fea2979a12e5',
  'reject_js': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]'},
 {'user_id': 'a7daceeb-1bdd-4c0c-82f4-b492df6bc50a',
  'reject_js': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]'},
 {'user_id': '0a7bf86f-826e-477b-9c25-44a48408dc08',
  'reject_js': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]'},
 {'user_id': 'cdbcec43-369d-47b0-8f62-5acaa015a19d',
  'reject_js': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]'},
 {'user_id': '4a6f1224-1272-4748-a365-624d9552b568',
  'reject_js': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]'},
 {'user_id': '1cfe555c-cf70-435b-aa7d-dda2a7e63b56',
  'reject_js': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]'}]

In [17]:
for a in reject_dict:
    print(a)

{'user_id': '206cf27c-aaf4-4a37-a7d1-c9f30106850c', 'reject_js': '[{"code": 1145, "message": "user_and_lead_phone_mismatch"}]'}
{'user_id': 'e25df091-4299-45f5-8d99-54de4ff3b337', 'reject_js': '[{"code": 1145, "message": "user_and_lead_phone_mismatch"}]'}
{'user_id': '3244d992-8691-4fb1-88a8-2a2d9fced9f5', 'reject_js': '[{"code": 1000, "message": "0 < age < 20 or age > 55"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]'}
{'user_id': '7447d9a7-075a-40de-9448-4dc1b13f1aa2', 'reject_js': '[{"code": 1000, "message": "0 < age < 20 or age > 55"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]'}
{'user_id': 'c1c48e87-1f6b-479e-a5a3-81afc1d56e7e', 'reject_js': '[{"code": 1000, "message": "0 < age < 20 or age > 55"}]'}
{'user_id': '354094cf-6f75-4de5-b975-fd9cb73a15c6', 'reject_js': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]'}
{'user_id': '8eb8d3e8-49f3-4a72-864c-5599cb291654', 'reject_js': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]'}
{'user_id': '156dd3dc-7d7b-4fa0-9b5c-fbf2ad40d1af', 'reject_js': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]'}
{'user_id': 'f86aadf6-520b-4e03-99eb-fea2979a12e5', 'reject_js': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]'}
{'user_id': 'a7daceeb-1bdd-4c0c-82f4-b492df6bc50a', 'reject_js': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]'}
{'user_id': '0a7bf86f-826e-477b-9c25-44a48408dc08', 'reject_js': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]'}
{'user_id': 'cdbcec43-369d-47b0-8f62-5acaa015a19d', 'reject_js': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]'}
{'user_id': '4a6f1224-1272-4748-a365-624d9552b568', 'reject_js': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]'}
{'user_id': '1cfe555c-cf70-435b-aa7d-dda2a7e63b56', 'reject_js': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]'}

In [10]:
data = {a['user_id']: a['reject_js'] for a in reject_dict}
data

{'206cf27c-aaf4-4a37-a7d1-c9f30106850c': '[{"code": 1145, "message": "user_and_lead_phone_mismatch"}]',
 '3244d992-8691-4fb1-88a8-2a2d9fced9f5': '[{"code": 1000, "message": "0 < age < 20 or age > 55"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]',
 '7447d9a7-075a-40de-9448-4dc1b13f1aa2': '[{"code": 1000, "message": "0 < age < 20 or age > 55"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]',
 '354094cf-6f75-4de5-b975-fd9cb73a15c6': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]',
 '8eb8d3e8-49f3-4a72-864c-5599cb291654': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]',
 '156dd3dc-7d7b-4fa0-9b5c-fbf2ad40d1af': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]',
 '0a7bf86f-826e-477b-9c25-44a48408dc08': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]',
 '4a6f1224-1272-4748-a365-624d9552b568': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]',
 '1cfe555c-cf70-435b-aa7d-dda2a7e63b56': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]',
 '9806f9f4-394e-471e-8192-940420e0659e': '[{"code": 1000, "message": "0 < age < 20 or age > 55"}]',
 '3359b002-ecc7-4c9c-ac62-08cc7c50e0f0': '[{"code": 1145, "message": "user_and_lead_phone_mismatch"}]',
 '87074e2a-7fd9-468a-9eb0-6f58ff449bf4': '[{"code": 1145, "message": "user_and_lead_phone_mismatch"}]',
 '1008d218-54f4-4064-a5dd-98e4e6d24ad8': '[{"code": 1145, "message": "user_and_lead_phone_mismatch"}]',
 '81a7c91f-c0d0-46bd-8572-923e71a09c7a': '[{"code": 1145, "message": "user_and_lead_phone_mismatch"}]',
 '789b738b-3f99-47dc-92f5-486d4fae1d38': '[{"code": 1145, "message": "user_and_lead_phone_mismatch"}]',
 '0eaf3f4f-7e4c-476b-9dc3-9a497a58ae13': '[{"code": 1145, "message": "user_and_lead_phone_mismatch"}]',
 '3a835e8f-0ee5-48a8-8506-00a7cf08d930': '[{"code": 1145, "message": "user_and_lead_phone_mismatch"}]',
 '50d36f2e-08e9-45e4-aa2c-235059d40de7': '[{"code": 1000, "message": "0 < age < 20 or age > 55"}]',
 '70d32d0d-ce31-40b2-b974-724f502146d8': '[{"code": 1145, "message": "user_and_lead_phone_mismatch"}]',
 'e25df091-4299-45f5-8d99-54de4ff3b337': '[{"code": 1145, "message": "user_and_lead_phone_mismatch"}]',
 'c1c48e87-1f6b-479e-a5a3-81afc1d56e7e': '[{"code": 1000, "message": "0 < age < 20 or age > 55"}]',
 'f86aadf6-520b-4e03-99eb-fea2979a12e5': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]',
 'a7daceeb-1bdd-4c0c-82f4-b492df6bc50a': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]',
 'cdbcec43-369d-47b0-8f62-5acaa015a19d': '[{"code": 1141, "message": "approved_lead_does_not_exists"}, {"code": 1143, "message": "pre_qualified_and_lead_pan_mismatch"}, {"code": 1145, "message": "user_and_lead_phone_mismatch"}]',
 'ee7a6923-bc92-42c3-9a1b-08752acd60a0': '[{"code": 1145, "message": "user_and_lead_phone_mismatch"}]',
 'dbb43dfd-2a56-4ab0-a7b3-fd5b3c920345': '[{"code": 1000, "message": "0 < age < 20 or age > 55"}]'}

In [9]:
rows = []
for k, v in data.items():
    reject = json.loads(v)
    for val in reject:
        rows.append({'user_id':k, "reject_rsn": val['message']})

NameError: name 'data' is not defined

In [8]:
df = pd.DataFrame(rows)

NameError: name 'rows' is not defined

In [ ]:
df

In [14]:
# Creating a dictionary
student = {
    "name": "Aditi",
    "age": 22,
    "major": "Computer Science",
    "is_graduated": False
}

# Accessing values
print(student["name"])      # Output: Aditi
print(student["age"])       # Output: 22

# Adding a new key-value pair
student["university"] = "IIT Delhi"

# Updating a value
student["age"] = 23

# Removing a key
del student["is_graduated"]

# Printing the whole dictionary
print(student)

Aditi
22
{'name': 'Aditi', 'age': 23, 'major': 'Computer Science', 'university': 'IIT Delhi'}

In [15]:
student

{'name': 'Aditi',
 'age': 23,
 'major': 'Computer Science',
 'university': 'IIT Delhi'}

In [20]:
for x in student:
    print(student[x])

Aditi
23
Computer Science
IIT Delhi

In [21]:
for x in student.keys():
    print(x)

name
age
major
university

In [23]:
for x,y in student.items():
    print(x,y)

name Aditi
age 23
major Computer Science
university IIT Delhi

In [24]:
def countdown(n):
    while n > 0:
        print(n)
        n -= 1
    print("Time's up!")

# Call the function
countdown(3)

3
2
1
Time's up!